---
- name: Setup Master
  hosts: master
  become: true
  tasks:
    - name: "Include acme.postgresql"
      include_role:
        name: "acme.postgresql"
      vars:
        postgresql_role: master

- name: Setup Replica
  hosts: replica
  become: true
  tasks:
    - name: "Include acme.postgresql"
      include_role:
        name: "acme.postgresql"
      vars:
        postgresql_role: replica
